name: Build iOS Tweak with Theos

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Tweak
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$PATH

      - name: Install Dependencies
        run: |
          brew update
          brew install dpkg

    #   - name: Install CCSupport Headers
    #     run: |
    #       git clone https://github.com/opa334/CCSupport.git $HOME/CCSupport
    #       export CCSUPPORT=$HOME/CCSupport
    #       export CPATH=$CCSUPPORT/include:$CPATH

      - name: Build Tweak
        run: make package