name: Build iOS Tweak with Theos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Tweak
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git /opt/theos
          export THEOS=/opt/theos
          export PATH=$THEOS/bin:$PATH

      - name: Install Dependencies
        run: |
          brew update
          brew install dpkg

      - name: Build Tweak
        run: make package
